//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerItem
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ItemId { get; set; }
        public int TransactionId { get; set; }
        public int Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
